/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiTeamColorsRouteImport } from './routes/api/team-colors'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiLiveEventTimeRouteImport } from './routes/api/live-event-time'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as ApiSyncPolymarketRouteImport } from './routes/api/sync/polymarket'
import { Route as ApiMarketsMarketIdRouteImport } from './routes/api/markets.$marketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiTeamColorsRoute = ApiTeamColorsRouteImport.update({
  id: '/api/team-colors',
  path: '/api/team-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveEventTimeRoute = ApiLiveEventTimeRouteImport.update({
  id: '/api/live-event-time',
  path: '/api/live-event-time',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSyncPolymarketRoute = ApiSyncPolymarketRouteImport.update({
  id: '/api/sync/polymarket',
  path: '/api/sync/polymarket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsMarketIdRoute = ApiMarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRoute
  '/api/sync/polymarket': typeof ApiSyncPolymarketRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRoute
  '/api/sync/polymarket': typeof ApiSyncPolymarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/auth/login': typeof AuthLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRoute
  '/api/sync/polymarket': typeof ApiSyncPolymarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/team-colors'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/team-colors'
    | '/auth/login'
    | '/'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
  id:
    | '__root__'
    | '/_public'
    | '/auth'
    | '/_public/dashboard'
    | '/_public/privacy'
    | '/_public/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/team-colors'
    | '/auth/login'
    | '/_public/'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiLiveEventTimeRoute: typeof ApiLiveEventTimeRoute
  ApiMarketsRoute: typeof ApiMarketsRouteWithChildren
  ApiTeamColorsRoute: typeof ApiTeamColorsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncPolymarketRoute: typeof ApiSyncPolymarketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/team-colors': {
      id: '/api/team-colors'
      path: '/api/team-colors'
      fullPath: '/api/team-colors'
      preLoaderRoute: typeof ApiTeamColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-event-time': {
      id: '/api/live-event-time'
      path: '/api/live-event-time'
      fullPath: '/api/live-event-time'
      preLoaderRoute: typeof ApiLiveEventTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/sync/polymarket': {
      id: '/api/sync/polymarket'
      path: '/api/sync/polymarket'
      fullPath: '/api/sync/polymarket'
      preLoaderRoute: typeof ApiSyncPolymarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets/$marketId': {
      id: '/api/markets/$marketId'
      path: '/$marketId'
      fullPath: '/api/markets/$marketId'
      preLoaderRoute: typeof ApiMarketsMarketIdRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDashboardRoute: PublicDashboardRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiMarketsRouteChildren {
  ApiMarketsMarketIdRoute: typeof ApiMarketsMarketIdRoute
}

const ApiMarketsRouteChildren: ApiMarketsRouteChildren = {
  ApiMarketsMarketIdRoute: ApiMarketsMarketIdRoute,
}

const ApiMarketsRouteWithChildren = ApiMarketsRoute._addFileChildren(
  ApiMarketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiLiveEventTimeRoute: ApiLiveEventTimeRoute,
  ApiMarketsRoute: ApiMarketsRouteWithChildren,
  ApiTeamColorsRoute: ApiTeamColorsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncPolymarketRoute: ApiSyncPolymarketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
