/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthUsernameRouteImport } from './routes/auth/username'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUserProfileRouteImport } from './routes/api/user-profile'
import { Route as ApiTeamColorsRouteImport } from './routes/api/team-colors'
import { Route as ApiParlayTeamsRouteImport } from './routes/api/parlay-teams'
import { Route as ApiPaperPortfolioRouteImport } from './routes/api/paper-portfolio'
import { Route as ApiMlbMarketsRouteImport } from './routes/api/mlb-markets'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiLiveEventTimeRouteImport } from './routes/api/live-event-time'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicPortfolioRouteImport } from './routes/_public/portfolio'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as ApiSyncPolymarketRouteImport } from './routes/api/sync/polymarket'
import { Route as ApiMarketsMarketIdRouteImport } from './routes/api/markets.$marketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSyncPolymarketScheduledRouteImport } from './routes/api/sync/polymarket.scheduled'
import { Route as ApiMarketsMarketIdCombosRouteImport } from './routes/api/markets.$marketId.combos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthUsernameRoute = AuthUsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user-profile',
  path: '/api/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamColorsRoute = ApiTeamColorsRouteImport.update({
  id: '/api/team-colors',
  path: '/api/team-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParlayTeamsRoute = ApiParlayTeamsRouteImport.update({
  id: '/api/parlay-teams',
  path: '/api/parlay-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperPortfolioRoute = ApiPaperPortfolioRouteImport.update({
  id: '/api/paper-portfolio',
  path: '/api/paper-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlbMarketsRoute = ApiMlbMarketsRouteImport.update({
  id: '/api/mlb-markets',
  path: '/api/mlb-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveEventTimeRoute = ApiLiveEventTimeRouteImport.update({
  id: '/api/live-event-time',
  path: '/api/live-event-time',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioRoute = PublicPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSyncPolymarketRoute = ApiSyncPolymarketRouteImport.update({
  id: '/api/sync/polymarket',
  path: '/api/sync/polymarket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsMarketIdRoute = ApiMarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => ApiMarketsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncPolymarketScheduledRoute =
  ApiSyncPolymarketScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => ApiSyncPolymarketRoute,
  } as any)
const ApiMarketsMarketIdCombosRoute =
  ApiMarketsMarketIdCombosRouteImport.update({
    id: '/combos',
    path: '/combos',
    getParentRoute: () => ApiMarketsMarketIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/portfolio': typeof PublicPortfolioRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/mlb-markets': typeof ApiMlbMarketsRoute
  '/api/paper-portfolio': typeof ApiPaperPortfolioRoute
  '/api/parlay-teams': typeof ApiParlayTeamsRoute
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/users': typeof ApiUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/username': typeof AuthUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRouteWithChildren
  '/api/sync/polymarket': typeof ApiSyncPolymarketRouteWithChildren
  '/api/markets/$marketId/combos': typeof ApiMarketsMarketIdCombosRoute
  '/api/sync/polymarket/scheduled': typeof ApiSyncPolymarketScheduledRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof PublicDashboardRoute
  '/portfolio': typeof PublicPortfolioRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/mlb-markets': typeof ApiMlbMarketsRoute
  '/api/paper-portfolio': typeof ApiPaperPortfolioRoute
  '/api/parlay-teams': typeof ApiParlayTeamsRoute
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/users': typeof ApiUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/username': typeof AuthUsernameRoute
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRouteWithChildren
  '/api/sync/polymarket': typeof ApiSyncPolymarketRouteWithChildren
  '/api/markets/$marketId/combos': typeof ApiMarketsMarketIdCombosRoute
  '/api/sync/polymarket/scheduled': typeof ApiSyncPolymarketScheduledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/portfolio': typeof PublicPortfolioRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/api/live-event-time': typeof ApiLiveEventTimeRoute
  '/api/markets': typeof ApiMarketsRouteWithChildren
  '/api/mlb-markets': typeof ApiMlbMarketsRoute
  '/api/paper-portfolio': typeof ApiPaperPortfolioRoute
  '/api/parlay-teams': typeof ApiParlayTeamsRoute
  '/api/team-colors': typeof ApiTeamColorsRoute
  '/api/user-profile': typeof ApiUserProfileRoute
  '/api/users': typeof ApiUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/username': typeof AuthUsernameRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/markets/$marketId': typeof ApiMarketsMarketIdRouteWithChildren
  '/api/sync/polymarket': typeof ApiSyncPolymarketRouteWithChildren
  '/api/markets/$marketId/combos': typeof ApiMarketsMarketIdCombosRoute
  '/api/sync/polymarket/scheduled': typeof ApiSyncPolymarketScheduledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/mlb-markets'
    | '/api/paper-portfolio'
    | '/api/parlay-teams'
    | '/api/team-colors'
    | '/api/user-profile'
    | '/api/users'
    | '/auth/login'
    | '/auth/username'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
    | '/api/markets/$marketId/combos'
    | '/api/sync/polymarket/scheduled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/mlb-markets'
    | '/api/paper-portfolio'
    | '/api/parlay-teams'
    | '/api/team-colors'
    | '/api/user-profile'
    | '/api/users'
    | '/auth/login'
    | '/auth/username'
    | '/'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
    | '/api/markets/$marketId/combos'
    | '/api/sync/polymarket/scheduled'
  id:
    | '__root__'
    | '/_public'
    | '/auth'
    | '/_public/dashboard'
    | '/_public/portfolio'
    | '/_public/privacy'
    | '/_public/terms'
    | '/api/live-event-time'
    | '/api/markets'
    | '/api/mlb-markets'
    | '/api/paper-portfolio'
    | '/api/parlay-teams'
    | '/api/team-colors'
    | '/api/user-profile'
    | '/api/users'
    | '/auth/login'
    | '/auth/username'
    | '/_public/'
    | '/api/auth/$'
    | '/api/markets/$marketId'
    | '/api/sync/polymarket'
    | '/api/markets/$marketId/combos'
    | '/api/sync/polymarket/scheduled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiLiveEventTimeRoute: typeof ApiLiveEventTimeRoute
  ApiMarketsRoute: typeof ApiMarketsRouteWithChildren
  ApiMlbMarketsRoute: typeof ApiMlbMarketsRoute
  ApiPaperPortfolioRoute: typeof ApiPaperPortfolioRoute
  ApiParlayTeamsRoute: typeof ApiParlayTeamsRoute
  ApiTeamColorsRoute: typeof ApiTeamColorsRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncPolymarketRoute: typeof ApiSyncPolymarketRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/username': {
      id: '/auth/username'
      path: '/username'
      fullPath: '/auth/username'
      preLoaderRoute: typeof AuthUsernameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-profile': {
      id: '/api/user-profile'
      path: '/api/user-profile'
      fullPath: '/api/user-profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-colors': {
      id: '/api/team-colors'
      path: '/api/team-colors'
      fullPath: '/api/team-colors'
      preLoaderRoute: typeof ApiTeamColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parlay-teams': {
      id: '/api/parlay-teams'
      path: '/api/parlay-teams'
      fullPath: '/api/parlay-teams'
      preLoaderRoute: typeof ApiParlayTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paper-portfolio': {
      id: '/api/paper-portfolio'
      path: '/api/paper-portfolio'
      fullPath: '/api/paper-portfolio'
      preLoaderRoute: typeof ApiPaperPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mlb-markets': {
      id: '/api/mlb-markets'
      path: '/api/mlb-markets'
      fullPath: '/api/mlb-markets'
      preLoaderRoute: typeof ApiMlbMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-event-time': {
      id: '/api/live-event-time'
      path: '/api/live-event-time'
      fullPath: '/api/live-event-time'
      preLoaderRoute: typeof ApiLiveEventTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio': {
      id: '/_public/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PublicPortfolioRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/sync/polymarket': {
      id: '/api/sync/polymarket'
      path: '/api/sync/polymarket'
      fullPath: '/api/sync/polymarket'
      preLoaderRoute: typeof ApiSyncPolymarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets/$marketId': {
      id: '/api/markets/$marketId'
      path: '/$marketId'
      fullPath: '/api/markets/$marketId'
      preLoaderRoute: typeof ApiMarketsMarketIdRouteImport
      parentRoute: typeof ApiMarketsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/polymarket/scheduled': {
      id: '/api/sync/polymarket/scheduled'
      path: '/scheduled'
      fullPath: '/api/sync/polymarket/scheduled'
      preLoaderRoute: typeof ApiSyncPolymarketScheduledRouteImport
      parentRoute: typeof ApiSyncPolymarketRoute
    }
    '/api/markets/$marketId/combos': {
      id: '/api/markets/$marketId/combos'
      path: '/combos'
      fullPath: '/api/markets/$marketId/combos'
      preLoaderRoute: typeof ApiMarketsMarketIdCombosRouteImport
      parentRoute: typeof ApiMarketsMarketIdRoute
    }
  }
}

interface PublicRouteChildren {
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicPortfolioRoute: typeof PublicPortfolioRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDashboardRoute: PublicDashboardRoute,
  PublicPortfolioRoute: PublicPortfolioRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthUsernameRoute: typeof AuthUsernameRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthUsernameRoute: AuthUsernameRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiMarketsMarketIdRouteChildren {
  ApiMarketsMarketIdCombosRoute: typeof ApiMarketsMarketIdCombosRoute
}

const ApiMarketsMarketIdRouteChildren: ApiMarketsMarketIdRouteChildren = {
  ApiMarketsMarketIdCombosRoute: ApiMarketsMarketIdCombosRoute,
}

const ApiMarketsMarketIdRouteWithChildren =
  ApiMarketsMarketIdRoute._addFileChildren(ApiMarketsMarketIdRouteChildren)

interface ApiMarketsRouteChildren {
  ApiMarketsMarketIdRoute: typeof ApiMarketsMarketIdRouteWithChildren
}

const ApiMarketsRouteChildren: ApiMarketsRouteChildren = {
  ApiMarketsMarketIdRoute: ApiMarketsMarketIdRouteWithChildren,
}

const ApiMarketsRouteWithChildren = ApiMarketsRoute._addFileChildren(
  ApiMarketsRouteChildren,
)

interface ApiSyncPolymarketRouteChildren {
  ApiSyncPolymarketScheduledRoute: typeof ApiSyncPolymarketScheduledRoute
}

const ApiSyncPolymarketRouteChildren: ApiSyncPolymarketRouteChildren = {
  ApiSyncPolymarketScheduledRoute: ApiSyncPolymarketScheduledRoute,
}

const ApiSyncPolymarketRouteWithChildren =
  ApiSyncPolymarketRoute._addFileChildren(ApiSyncPolymarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiLiveEventTimeRoute: ApiLiveEventTimeRoute,
  ApiMarketsRoute: ApiMarketsRouteWithChildren,
  ApiMlbMarketsRoute: ApiMlbMarketsRoute,
  ApiPaperPortfolioRoute: ApiPaperPortfolioRoute,
  ApiParlayTeamsRoute: ApiParlayTeamsRoute,
  ApiTeamColorsRoute: ApiTeamColorsRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncPolymarketRoute: ApiSyncPolymarketRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
